name: spotify
description: "Spotify App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.2.3
  hydrated_bloc: ^10.1.1
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 300
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/splash_ios_android_12.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/play-store-icon-launcher.png"
